"""create initial tables

Revision ID: 5096a945e550
Revises: 
Create Date: 2026-07-10 10:47:55.939013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5096a945e550'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('products',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('main_accords', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('price_aed', sa.Float(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_aed', sa.Float(), nullable=False),
    sa.Column('line_total_aed', sa.Float(), nullable=False),
    sa.Column('balance_after_aed', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['products.item_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('conversations')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
